spring:
  thymeleaf:
    cache: false
    mode: "HTML"
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/merucari
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
server:
  servlet:
    context-path: 
    
    
        